# This is a placeholder so actions won't default to a getting started page

name: Deploy my Lambda Function

on: push

jobs:
  init:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: install libraries
        run: |
          cd function
          python -m pip install --upgrade pip
          if [ -f requirements.txt]; then pip install -r requirements.txt -t .; fi
      - name: Create zip bundle
        run: |
          cd function
          zip -r ../${{ github.sha }}.zip .
      - name: Archieve artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
          
        
